language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

install:
  - nvm use && npm i

script:
  - node_modules/eslint/bin/eslint.js --fix .
  - cd install && chmod +x demo && ./demo && cd demo-app && npm run test
