language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - . ~/.nvm/nvm.sh && nvm use && npm i

script:
  - node_modules/eslint/bin/eslint.js --fix .
  - cd install && chmod +x demo && ./demo && cd demo-app
  - nvm use && npm i && npm run test
