language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - . ~/.nvm/nvm.sh && nvm i 6.10

script:
  - npm i > /dev/null && node_modules/eslint/bin/eslint.js --fix .
  - projectName="ci-app"
  - projectDescription="continuous integration application"
  - projectLicense="MIT"
  - projectAuthor="rectangular"
  - mkdir "$projectName" && cd "$projectName"
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null
  - node package.js "$projectName" "$projectDescription" "$projectLicense" "$author" && rm package.js
  - npm i abbotto/rectangular
  - mkdir node_modules/rectangular/tmp
  - mkdir node_modules/rectangular/tmp/project
  - cp -a node_modules/rectangular/install/project/. node_modules/rectangular/tmp/project/
  - cp package.json node_modules/rectangular/tmp/project/
  - cd node_modules/rectangular/tmp/project
  - npm i --save bootstrap angular-strap
  - npm i --save angular-material
  - npm i --save bluebird
  - npm i --save moment
  - npm i --save angular-moment
  - npm i --save lodash
  - npm i --save angular-translate
  - npm i --save restangular
  - npm i --save ng-file-upload
  - cd ../../
  - cp .envrc .env
  - cp -a install/extra/extension/ng-strap/. tmp/project/app/extension/ng-strap/
  - cp -a install/extra/shared/service/ui/bootstrap/. tmp/project/app/shared/service/ui/
  - cp -a install/extra/extension/angular-material/. tmp/project/app/extension/angular-material/
  - cp -a install/extra/shared/service/ui/material-design/. tmp/project/app/shared/service/ui/
  - cp -a install/extra/extension/bluebird/. tmp/project/app/extension/bluebird/
  - cp -a install/extra/shared/service/promise/. tmp/project/app/shared/service/promise/
  - cp -a install/extra/extension/moment/. tmp/project/app/extension/moment/
  - cp -a install/extra/shared/service/date/. tmp/project/app/shared/service/date/
  - cp -a install/extra/extension/lodash/. tmp/project/app/extension/lodash/
  - cp -a install/extra/shared/service/_/. tmp/project/app/shared/service/_/
  - cp -a install/extra/extension/angular-translate/. tmp/project/app/extension/angular-translate/
  - cp -a install/extra/shared/service/locale/. tmp/project/app/shared/service/locale/
  - cp -a install/extra/extension/restangular/. tmp/project/app/extension/restangular/
  - cp -a install/extra/shared/service/promise/. tmp/project/app/shared/service/promise/
  - cp -a install/extra/extension/ng-file-upload/. tmp/project/app/extension/ng-file-upload/
  - cp -a install/extra/shared/service/upload/. tmp/project/app/shared/service/upload/
  - cd ../../
  - cd node_modules/rectangular/ && npm i && cd ../../
  - cp -a node_modules/rectangular/tmp/project/. .
  - cp .envrc .env
  - cd node_modules/rectangular && rm -rf tmp && mkdir tmp && cd ../../
  - . ~/.nvm/nvm.sh && nvm use && npm i
  - node_modules/karma/bin/karma start karma.conf.js
