language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

script:
  - . ~/.nvm/nvm.sh && nvm use && npm i && node_modules/eslint/bin/eslint.js --fix .
  - . ~/.nvm/nvm.sh && nvm use && npm i && cd install && chmod +x demo && ./demo
  - cd demo-app && . ~/.nvm/nvm.sh && nvm use && npm i && npm run test
