language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

install:
  - cd ..
  - mkdir testApp
  - cd testApp
  - npm init --yes
  - npm i https://github.com/abbotto/rectangular.git
  - cp -R node_modules/rectangular/project/ .
  - npm run test
  - cd ../rectangular
  - rm -rf ../testApp

script: npm start
