language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
  - node_modules/eslint/bin/eslint.js --fix .
  - cd install && chmod +x demo && ./demo && cd demo && npm run test
