language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

script:
  - node_modules/eslint/bin/eslint.js --fix .
  - cd install && chmod +x demo && ./demo && cd demo && nvm i 6.10 && npm i && npm run test
