language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

script:
  - . ~/.nvm/nvm.sh && nvm use && npm i && node_modules/eslint/bin/eslint.js --fix .
  - cd demo-app && . ~/.nvm/nvm.sh && nvm use && npm i && npm run test
  - projectName="ci-app"
  - projectDescription="continuous integration application"
  - projectLicense="MIT"
  - projectAuthor="rectangular"
  - mkdir "$projectName"
  - cd "$projectName"
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - . ~/.nvm/nvm.sh && nvm i $PACKAGE_VERSION
  - node package.js "$projectName" "$projectDescription" "$projectLicense" "$author"
  - rm package.js
  - npm i abbotto/rectangular > /dev/null
  - mkdir node_modules/rectangular/tmp && mkdir node_modules/rectangular/tmp/project
  - cp -R node_modules/rectangular/install/project/ node_modules/rectangular/tmp/project
  - cp package.json node_modules/rectangular/tmp/project/
  - cd node_modules/rectangular/ && . ~/.nvm/nvm.sh && nvm use && npm i && cd ../../
  - cp -R node_modules/rectangular/tmp/project/*/**/ .
  - cd node_modules/rectangular && rm -rf tmp && mkdir tmp && . ~/.nvm/nvm.sh && nvm use && npm i && cd ../../
  - . ~/.nvm/nvm.sh && nvm use && npm i && npm run test
