language: node_js

notifications:
  email: false
  
sudo: false

node_js:
  - "6.11"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
- |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '(\.js)|(\.json)|(\.html)|(\.ts)/' || {
      echo "No {html|js|json|ts} files were updated - stopping build process."
      exit
    }

script:
  - npm i > /dev/null && node_modules/eslint/bin/eslint.js --quiet --fix --ext .json --ext .js .
  - projectName="ci-app"
  - projectDescription="continuous integration application"
  - projectLicense="MIT"
  - projectAuthor="rectangular"
  - mkdir "$projectName" && cd "$projectName"
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/extra.js > /dev/null
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null
  - node package.js "$projectName" "$projectDescription" "$projectLicense" "$author" && rm package.js
  - npm i
  - cp -a node_modules/rectangular/install/project/. .
  - npm i --save bootstrap angular-strap angular-material bluebird d3 moment angular-moment lodash angular-translate restangular socket.io ng-file-upload teleprint
  - mkdir app/extension/ui/
  - mkdir app/extension/promise/
  - mkdir app/extension/chart/
  - mkdir app/extension/date/
  - mkdir app/extension/_/
  - mkdir app/extension/locale/
  - mkdir app/extension/rest/
  - mkdir app/extension/socket/
  - mkdir app/extension/upload/
  - mkdir app/extension/print/
  - cp -a node_modules/rectangular/install/extra/extension/ui/bootstrap/. app/extension/ui/
  - cp -a node_modules/rectangular/install/extra/extension/ui/material-design/. app/extension/ui/
  - cp -a node_modules/rectangular/install/extra/extension/promise/. app/extension/promise/
  - cp -a node_modules/rectangular/install/extra/extension/chart/. app/extension/chart/
  - cp -a node_modules/rectangular/install/extra/extension/date/. app/extension/date/
  - cp -a node_modules/rectangular/install/extra/extension/_/. app/extension/_/
  - cp -a node_modules/rectangular/install/extra/extension/locale/. app/extension/locale/
  - cp -a node_modules/rectangular/install/extra/extension/rest/. app/extension/rest/
  - cp -a node_modules/rectangular/install/extra/extension/socket/. app/extension/socket/
  - cp -a node_modules/rectangular/install/extra/extension/upload/. app/extension/upload/
  - cp -a node_modules/rectangular/install/extra/extension/print/. app/extension/print/
  - npm run test
