language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

install:
  - . ~/.nvm/nvm.sh && nvm use && npm i

before_script:
  - . ~/.nvm/nvm.sh && nvm use && npm i

script:
  - . ~/.nvm/nvm.sh && nvm use && npm i && node_modules/eslint/bin/eslint.js --fix .
  - . ~/.nvm/nvm.sh && nvm use && npm i && cd install && chmod +x demo && ./demo && cd demo-app && nvm use && npm i && npm run test
