language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - . ~/.nvm/nvm.sh && nvm i 6.10

script:
  - npm i && node_modules/eslint/bin/eslint.js --fix .
  - projectName="ci-app"
  - projectDescription="continuous integration application"
  - projectLicense="MIT"
  - projectAuthor="rectangular"
  - mkdir "$projectName" && cd "$projectName"
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
  - curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null
  - node package.js "$projectName" "$projectDescription" "$projectLicense" "$author" && rm package.js
  - npm i abbotto/rectangular > /dev/null
  - mkdir node_modules/rectangular/tmp
  - mkdir node_modules/rectangular/tmp/project
  - cp -a node_modules/rectangular/install/project/. node_modules/rectangular/tmp/project/
  - cp package.json node_modules/rectangular/tmp/project/
  - cd node_modules/rectangular/tmp/project
  - npm i --save bootstrap angular-strap
  - npm i --save angular-material
  - npm i --save bluebird
  - npm i --save moment
  - npm i --save angular-moment
  - npm i --save lodash
  - npm i --save angular-translate
  - npm i --save restangular
  - npm i --save ng-file-upload
  - cd ../../../../
  - cd node_modules/rectangular/ && npm i && cd ../../
  - cp -a node_modules/rectangular/tmp/project/. .
  - cd node_modules/rectangular && rm -rf tmp && mkdir tmp && cd ../../
  - . ~/.nvm/nvm.sh && nvm use && npm i
  - node_modules/karma/bin/karma start karma.conf.js
