#!/bin/bash

echo ""
echo "---------------------"
echo "RECTANGULAR INSTALLER"
echo "---------------------"

echo ""
echo "What is your project name?"

read projectName

echo ""
echo "Installing $projectName"

mkdir $projectName
cd $projectName

. ~/.nvm/nvm.sh
npm init --yes
npm i https://github.com/abbotto/rectangular.git

cd node_modules/rectangular/

nvm use
npm i
node dev/task/vendor.install.js

cd ../../

cp -R node_modules/rectangular/project/ .

npm run setup

echo ""
echo "Finished. Thank you for choosing Rectangular."
