#!/bin/bash

echo "What is your project name?"

read projectName

echo "Installing $projectName"

mkdir $projectName

cd $projectName

npm init --yes

npm i https://github.com/abbotto/rectangular.git

cd node_modules/rectangular/

nvm use

npm i

node dev/task/vendor.install.js

cp -R node_modules/rectangular/project/ .

npm run setup

echo "Finished. Thank you for choosing Rectangular."
