#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}---------------------${NC}"
echo -e "RECTANGULAR INSTALLER"
echo -e "${YELLOW}---------------------${NC}"

echo ""
echo -e "prompt: ${RED}What is your project name?${NC}"

read projectName

echo ""
echo -e "prompt: ${RED}Please describe your project${NC}"

read projectDescription

echo ""
echo -e "${YELLOW}Installing $projectName...${NC}"

mkdir $projectName
cd $projectName

. ~/.nvm/nvm.sh > /dev/null
npm init --yes > /dev/null
npm i https://github.com/abbotto/rectangular.git > /dev/null

cd node_modules/rectangular/
mkdir tmp && mkdir tmp/project
cp -R install/project/ tmp/project
node install/package.js $projectName $projectDescription
cp tmp/project/package.json ../../

nvm use > /dev/null
npm i
node install/extra.js

cd ../../
cp -R node_modules/rectangular/tmp/project/ .

npm run setup

echo ""
echo -e "${YELLOW}Finished. Thank you for choosing Rectangular.${NC}"
