#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}---------------------${NC}"
echo -e "${YELLOW}RECTANGULAR INSTALLER${NC}"
echo -e "${YELLOW}---------------------${NC}"

# Get the project name
echo ""
echo -e "prompt: ${RED}Project Name${NC}"

read projectName

# Get the project description
echo ""
echo -e "prompt: ${RED}Project Description${NC}"

read projectDescription

# Get the project license
echo ""
echo -e "prompt: ${RED}Project License${NC}"

read projectLicense

# Get the project author
echo ""
echo -e "prompt: ${RED}Project Author${NC}"

read projectAuthor

echo ""
echo -e "${YELLOW}Installing $projectName...${NC}"
echo ""

# Create the project directory
mkdir "$projectName"
cd "$projectName"

# NPM setup
. ~/.nvm/nvm.sh
nvm i 8.9

# Fetch required files
curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/extension.js > /dev/null
curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null

echo ""
echo -e "Fetching Rectangular..."
mkdir -p tmp
git clone https://github.com/abbotto/rectangular.git

echo -e "Copy project files..."
cp -a tmp/rectangular/install/project/. .
cp .envrc .env

echo -e "Add the project details..."
node package.js "$projectName" "$projectDescription" "$projectLicense" "$author"
rm package.js

echo -e "Run the extras installer..."
node extension.js
rm extension.js

echo -e "Building the app..."
npm i
node composer.js --build --production

rm -rf tmp/rectangular
npm i

cd node_modules/rectangular/
cp .envrc .env
npm i

# Completed
echo ""
echo -e "${YELLOW}Finished. Thank you for choosing Rectangular.${NC}"
