#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}---------------------${NC}"
echo -e "${YELLOW}RECTANGULAR INSTALLER${NC}"
echo -e "${YELLOW}---------------------${NC}"

# Get the project name
echo ""
echo -e "prompt: ${RED}Project Name${NC}"

read projectName

# Get the project description
echo ""
echo -e "prompt: ${RED}Project Description${NC}"

read projectDescription

# Get the project license
echo ""
echo -e "prompt: ${RED}Project License${NC}"

read projectLicense

# Get the project author
echo ""
echo -e "prompt: ${RED}Project Author${NC}"

read projectAuthor

echo ""
echo -e "${YELLOW}Installing $projectName...${NC}"
echo ""

# Create the project directory
mkdir "$projectName"
cd "$projectName"

# Initialize package.json
curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/package.js > /dev/null
curl -O -s https://raw.githubusercontent.com/abbotto/rectangular/master/install/project/package.json > /dev/null

echo -e "Add the project details..."
node package.js "$projectName" "$projectDescription" "$projectLicense" "$author"
rm package.js

echo -e "Grab Rectangular..."
npm i --save-dev abbotto/rectangular > /dev/null

echo -e "Setup temporary project files and directories..."
mkdir node_modules/rectangular/tmp
mkdir node_modules/rectangular/tmp/project
cp -a node_modules/rectangular/install/project/. node_modules/rectangular/tmp/project/
cp package.json node_modules/rectangular/tmp/project/

echo -e "Initialize Rectangular and run the extras installer..."
cd node_modules/rectangular/
cp .envrc .env
npm i
node install/extra.js
cd ../../

echo -e "Copy the project files and run the setup build..."
cp -a node_modules/rectangular/tmp/project/. .

echo -e "Build the app..."
npm i
npm run build

# Completed
echo ""
echo -e "${YELLOW}Finished. Thank you for choosing Rectangular.${NC}"
